# Generated by Django 3.2.16 on 2023-04-03 22:02

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('following_id', django.db.models.expressions.F('user')), _negated=True), name='subscription_restriction_to_self'),
        ),
    ]
